### ISSUE TITLE
metrics exporter is crashing periodically

### ISSUE THREAD

**Issue by krancour** [brigadecore/brigade-metrics#10]
This was first observed when a heavier and more consistent load was applied to the Brigade2 dogfood cluster.

```
$ kubectl logs -f brigade-metrics-exporter-795fdb5446-s5ldx -n brigade-metrics 
2021/07/27 18:57:18 Starting Brigade Metrics Exporter -- version v0.9.0-alpha.1 -- commit e605d87
2021/07/27 18:57:18 Server is listening without TLS on 0.0.0.0:8080
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86ff70]

goroutine 13 [running]:
main.(*metricsExporter).recordMetrics(0xc000180480)
	/src/exporter/metrics_exporter.go:132 +0xb10
main.(*metricsExporter).run(0xc000180480, 0x9f3b40, 0xc0000b8000)
	/src/exporter/metrics_exporter.go:88 +0x8d
created by main.main
	/src/exporter/main.go:35 +0x2c6
```

**Comment by willie-yao** [comment]
Since we discovered that this bug was caused by an older build of brigade-metrics and didn't happen again with the most updated version, should we close this issue?

**Comment by krancour** [comment]
Leave it open for now and I'll double-check yhe current status of the metrics exporter in the dogfood cluster as soon as I'm able.

**Comment by krancour** [comment]
Closing this as this has shown itself to no longer be an issue.
